version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    networks:
      - encoder

  minio:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_volume:/data
    networks:
      - encoder

networks:
  encoder:

volumes:
  minio_volume:
